---
name: Lint

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'release/v**'
      - 'run-ci/**'
    tags:
      - 'v*'
  pull_request:

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3 python3-pip

      - name: Install required pip packages
        run: pip3 install -r requirements.txt

      - name: pycodestyle test
        run: bash tests/lint/pycodestyle/run.sh .

  pylint:
    name: pylint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3 python3-pip

      - name: Install required pip packages
        run: pip3 install -r requirements.txt

      - name: pylint test
        run: bash tests/lint/pylint/run.sh .

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install -g markdownlint-cli

      - name: markdownlint test
        run: bash tests/lint/markdownlint/run.sh .

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3 python3-pip

      - name: Install required pip packages
        run: pip3 install -r requirements.txt

      - name: yamllint test
        run: bash tests/lint/yamllint/run.sh .

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck

      - name: shellcheck test
        run: bash tests/lint/shellcheck/run.sh .
